### ISSUE TITLE
stop working in  Home Assistant 2023.5.4

### ISSUE THREAD

**Issue by artkli** [mercs600/ha-adb_service#14]
after ugrade of HA, component adb_service stops working

-- 

Home Assistant 2023.5.4 Supervisor 2023.04.1 Operating System 10.2 Interfejs użytkownika: 20230503.3 - latest 

-- 

Logger: homeassistant.setup
Source: custom_components/adb_service/__init__.py:15
Integration: adb_service ([documentation](https://github.com/mercs600/ha-adb_service))
First occurred: 2 czerwca 2023 19:56:07 (1 occurrences)
Last logged: 2 czerwca 2023 19:56:07
Error during setup of component adb_service

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x65c57520>: Failed to establish a new connection: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.115', port=8080): Max retries exceeded with url: /system/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x65c57520>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 257, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/adb_service/__init__.py", line 15, in setup
    statusResponse = requests.get('http://' + str(host) + ':8080/system/version')
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.115', port=8080): Max retries exceeded with url: /system/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x65c57520>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

**Comment by aplok** [comment]
NIe działa z 2024.3.1 , dlaczego?

**Comment by mercs600** [comment]
Hi, unfortunately, I no longer have the nc+ decoder, so I am unable to debug the problem. 

If someone from the community has solved the issue, please submit a PR.

**Comment by stepek** [comment]
@mercs600 have you some documentation for api? or are you reverse engineered  it?

**Comment by mercs600** [comment]
@stepek I did it by reverse engineering, listening to mobile app requests on a local proxy.
