### ISSUE TITLE
Issue with registering service 

### ISSUE THREAD

**Issue by Rrapa** [mercs600/ha-adb_service#4]
Hello 
Trying to integrate that service but getting following error:
Invalid config
The following integrations and platforms could not be set up:

adb_service

Logger: homeassistant.setup
Source: custom_components/adb_service/__init__.py:16 
First occurred: 20:55:01 (1 occurrences) 
Last logged: 20:55:01

Error during setup of component adb_service
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 241, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/adb_service/__init__.py", line 16, in setup
    statusResponse = statusResponse.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any idea why ? or simply ADB model is not supported?

**Comment by mercs600** [comment]
@Rrapa could you check it with latest version ?

**Comment by Rrapa** [comment]
Looks good now .. feel free to close. Thank you ! and . .Happy New Year !
